version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskflow_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
      POSTGRES_DB: taskflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: taskflow_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
